I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 757, in script
    show stepan happy at back:
  File "game/script.rpy", line 757, in <module>
    show stepan happy at back:
NameError: name 'back' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 757, in script
    show stepan happy at back:
  File "D:\renpy-8.0.3-sdk\renpy\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.0.3-sdk\renpy\renpy\ast.py", line 1367, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\renpy-8.0.3-sdk\renpy\renpy\ast.py", line 1367, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "D:\renpy-8.0.3-sdk\renpy\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy-8.0.3-sdk\renpy\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 757, in <module>
    show stepan happy at back:
NameError: name 'back' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Capybara 1.0
Tue Dec 20 20:34:08 2022
